### ISSUE TITLE
Some improvements

### ISSUE THREAD

**Issue by ytaylordev** [VanesaGR/Check-the-number#1]
Really cool job @VanesaGR !!!

Here you have some tips to improve the exercise:

### JavaScript: basic
- [x] If we repeat several times `parseInt(value)` within a function it is better set it in a constant.

### Good practices
- [x] Try to improve your commits messages. "html, css, js" is a bit poor

### Structure
- [x] CSS and JS path must to start with `./`.

### HTML

- [x] Use placeholder attribute instead of value one to show a field's hint.
- [x] Inputs must have a type attribute set to a valid value (text, number, mail, button..).

### Further challenges

Then you can improve the game as you please, here you have some ideas:

- Add new feedback when the number is bigger than 100 or smaller than 0.
- Manage when the user hits the button and the input is empty.
- Make the input work when hitting enter key.
- Add a reset button that cleans the input, the counter, writes the initial feedback and generates a new random number to play again!
- Whatever you want!

### Call to action

Let me know if you have any doubts ;)

Go for it!!

> Do not close this issue until your teacher asks you to

**Comment by VanesaGR** [comment]
I really don't know how to improve the remaining issues. The first one remaining according to its dificulty (maybe it's just me) and the last two ones because I do not know why you wrote them to me.

Thank you!
